<h1><?=$page->title?></h1>

<?=$page->body?> <br><br>

<p>Leider gibt es derzeit einen Fehler in unserem Kontaktformular. Wir Bitten daher um eine E-Mail an <a href="mailto:info@freifunk-myk.de">info@freifunk-myk.de</a>.</p>
<!--
<form id="myForm" action="../scripts/mail.php" method="post" data-abide>  
<div class="contctform">
<div class="name-field">
<label>Name*</label>
<input id="name" type="text" placeholder="Name" required pattern="[a-zA-Z]+">
<small class="error">Bitte gib deinen Namen an.</small>
</div>

<div class="email-field">
<label>Email*</label>
<input id="email" type="email" placeholder="username@address.com" required>
<small class="error">Bitte gib deine E-Mail Adresse ein sonst können wir nicht Antworten.</small>
</div>

<label>Deine Anfrage*</label>
<small class="error">Ohne Anfrage macht das Absenden wenig Sinn.</small>
<textarea id="message" placeholder="Nachricht hier eingeben." required></textarea>

<input type="submit" class="nice blue radius button" value="Absenden"></button></a>
</div>
</form>-->
